create table reiziger
(
    geboortedatum date,
    reiziger_id integer generated by default as identity
        constraint reiziger_id
            primary key,
    tussenvoegsel varchar(10),
    voorletters varchar(10) not null,
    achternaam varchar(255) not null
);

alter table reiziger owner to postgres;

create table adres
(
    adres_id integer not null
        constraint adres_id
            primary key,
    postcode varchar(10) not null,
    huisnummer varchar(10) not null,
    straat varchar(255) not null,
    woonplaats varchar(255) not null,
    reiziger_id integer not null
        constraint reiziger_id
            references reiziger
);

alter table adres owner to postgres;

create table ov_chipkaart
(
    kaart_nummer integer not null
        constraint kaart_nummer
            primary key,
    geldig_tot date not null,
    klasse integer not null,
    saldo numeric(16,2) not null,
    reiziger_id integer not null
        constraint reiziger_id
            references reiziger
);

alter table ov_chipkaart owner to postgres;

create table product
(
    product_nummer integer not null
        constraint product_nummer
            primary key,
    naam varchar(30) not null,
    beschrijving varchar(512) not null,
    prijs numeric(16,2) not null
);

alter table product owner to postgres;

create table ov_chipkaart_product
(
    kaart_nummer integer not null
        constraint kaart_nummer
            references ov_chipkaart,
    product_nummer integer not null
        constraint product_nummer
            references product,
    status varchar(10),
    last_update date,
    constraint kaart_product_nummer
        primary key (kaart_nummer, product_nummer)
);

alter table ov_chipkaart_product owner to postgres;

