create table reiziger
(
    geboortedatum date,
    reiziger_id   integer generated by default as identity
        constraint reiziger_id
            primary key,
    tussenvoegsel varchar(10),
    voorletters   varchar(10)  not null,
    achternaam    varchar(255) not null
);

alter table reiziger
    owner to postgres;

INSERT INTO public.reiziger (geboortedatum, reiziger_id, tussenvoegsel, voorletters, achternaam) VALUES ('1998-02-12', 1, 'van', 'TFP', 'Oort');
INSERT INTO public.reiziger (geboortedatum, reiziger_id, tussenvoegsel, voorletters, achternaam) VALUES ('1968-08-19', 3, null, 'A', 'Donk');
INSERT INTO public.reiziger (geboortedatum, reiziger_id, tussenvoegsel, voorletters, achternaam) VALUES ('1982-11-21', 4, null, 'TJ', 'Muller');
INSERT INTO public.reiziger (geboortedatum, reiziger_id, tussenvoegsel, voorletters, achternaam) VALUES ('1962-02-02', 5, 'van der', 'H', 'Ridder');
INSERT INTO public.reiziger (geboortedatum, reiziger_id, tussenvoegsel, voorletters, achternaam) VALUES ('1981-03-14', 77, 'van', 'S', 'Boers');